name: Deploy Bicep Infra

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Install Bicep CLI and yq
      - name: Install Bicep and yq
        run: |
          az bicep install
          sudo apt-get install -y yq

      # Deploy Bicep file
      - name: deploy bicep
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: ./infra/main.bicep
          resourceGroupName: "rg-DeadlineApp"
          parameters: ./infra/bicep.parameters.yml
          failOnStdErr: false